# Generated by Django 4.1.3 on 2022-12-03 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snacks_app', '0002_alter_snack_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='snack',
            name='img_url',
            field=models.TextField(default='NO image available!'),
        ),
        migrations.AlterField(
            model_name='snack',
            name='name',
            field=models.CharField(default='Snack', help_text='snaks', max_length=64),
        ),
    ]
